/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type ServicesKey =
    | "lazerna-korekcziya-zoru"
    | "perevirka-zoru"
    | "likuvannya-katarakti"
    | "syndrom-sukhoho-oka"
    | "dityache-viddilennya"
    | "likuvannya-keratokonusa"
    | "lazerne-likuvannya-zahvoryuvan-oka"
    | "refrakczijna-lensektomiya"
    | "vitreoretinalna-hirurgiya"
    | "intravitrealni-inekczii"
    | "hirurgichne-likuvannya-glaukomi"
    | "likuvannya-kosookosti"
    | "hirurgiya-povik-i-konyunktivi"
    | "anesteziologichnij-posibnik"
    | "ksenonoterapiya";

export type PortableText = Array<{
    children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: null;
    level?: number;
    _type: "block";
    _key: string;
}>;

export type PriceBlock = {
    _type: "priceBlock";
    servicesKey?: ServicesKey;
    icon?: {
        asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
    };
    list?: Array<
        {
            _key: string;
        } & PriceItem
    >;
    linkToPage?: string;
    servicesName?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    servicesDescription?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
};

export type PriceItem = {
    _type: "priceItem";
    serviceName?: Array<
        {
            _key: string;
        } & InternationalizedArrayStringValue
    >;
    price?: number;
    lowerPriceLimit?: boolean;
    discountPrice?: number;
    lowerDiscountLimit?: boolean;
    specialPrice?: boolean;
    new?: boolean;
    serviceDescription?: Array<
        {
            _key: string;
        } & InternationalizedArrayPortableTextValue
    >;
};

export type PricesPage = {
    _id: string;
    _type: "pricesPage";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    priceBlocks?: Array<
        {
            _key: string;
        } & PriceBlock
    >;
};

export type InternationalizedArrayPortableTextValue = {
    _type: "internationalizedArrayPortableTextValue";
    value?: PortableText;
};

export type InternationalizedArrayTextValue = {
    _type: "internationalizedArrayTextValue";
    value?: string;
};

export type InternationalizedArrayStringValue = {
    _type: "internationalizedArrayStringValue";
    value?: string;
};

export type InternationalizedArrayPortableText = Array<
    {
        _key: string;
    } & InternationalizedArrayPortableTextValue
>;

export type InternationalizedArrayText = Array<
    {
        _key: string;
    } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
    {
        _key: string;
    } & InternationalizedArrayStringValue
>;

export type SanityImagePaletteSwatch = {
    _type: "sanity.imagePaletteSwatch";
    background?: string;
    foreground?: string;
    population?: number;
    title?: string;
};

export type SanityImagePalette = {
    _type: "sanity.imagePalette";
    darkMuted?: SanityImagePaletteSwatch;
    lightVibrant?: SanityImagePaletteSwatch;
    darkVibrant?: SanityImagePaletteSwatch;
    vibrant?: SanityImagePaletteSwatch;
    dominant?: SanityImagePaletteSwatch;
    lightMuted?: SanityImagePaletteSwatch;
    muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
    _type: "sanity.imageDimensions";
    height?: number;
    width?: number;
    aspectRatio?: number;
};

export type SanityImageHotspot = {
    _type: "sanity.imageHotspot";
    x?: number;
    y?: number;
    height?: number;
    width?: number;
};

export type SanityImageCrop = {
    _type: "sanity.imageCrop";
    top?: number;
    bottom?: number;
    left?: number;
    right?: number;
};

export type SanityFileAsset = {
    _id: string;
    _type: "sanity.fileAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
    _id: string;
    _type: "sanity.imageAsset";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    originalFilename?: string;
    label?: string;
    title?: string;
    description?: string;
    altText?: string;
    sha1hash?: string;
    extension?: string;
    mimeType?: string;
    size?: number;
    assetId?: string;
    uploadId?: string;
    path?: string;
    url?: string;
    metadata?: SanityImageMetadata;
    source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
    _type: "sanity.imageMetadata";
    location?: Geopoint;
    dimensions?: SanityImageDimensions;
    palette?: SanityImagePalette;
    lqip?: string;
    blurHash?: string;
    hasAlpha?: boolean;
    isOpaque?: boolean;
};

export type Geopoint = {
    _type: "geopoint";
    lat?: number;
    lng?: number;
    alt?: number;
};

export type Slug = {
    _type: "slug";
    current?: string;
    source?: string;
};

export type SanityAssetSourceData = {
    _type: "sanity.assetSourceData";
    name?: string;
    id?: string;
    url?: string;
};

export type AllSanitySchemaTypes =
    | ServicesKey
    | PortableText
    | PriceBlock
    | PriceItem
    | PricesPage
    | InternationalizedArrayPortableTextValue
    | InternationalizedArrayTextValue
    | InternationalizedArrayStringValue
    | InternationalizedArrayPortableText
    | InternationalizedArrayText
    | InternationalizedArrayString
    | SanityImagePaletteSwatch
    | SanityImagePalette
    | SanityImageDimensions
    | SanityImageHotspot
    | SanityImageCrop
    | SanityFileAsset
    | SanityImageAsset
    | SanityImageMetadata
    | Geopoint
    | Slug
    | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: pricesPageQuery
// Query: *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[] {servicesKey, "servicesName": servicesName[_key == $language][0].value, linkToPage,    "list":list[]{new, price, lowerPriceLimit, discountPrice, lowerDiscountLimit, specialPrice,                 "serviceName": serviceName[_key == $language][0].value,                 "serviceDescription":serviceDescription[_key == $language][0].value},    "servicesDescription":servicesDescription[_key == $language][0].value }
export type PricesPageQueryResult = Array<{
    servicesKey: ServicesKey | null;
    servicesName: string | null;
    linkToPage: string | null;
    list: Array<{
        new: boolean | null;
        price: number | null;
        lowerPriceLimit: boolean | null;
        discountPrice: number | null;
        lowerDiscountLimit: boolean | null;
        specialPrice: boolean | null;
        serviceName: string | null;
        serviceDescription: PortableText | null;
    }> | null;
    servicesDescription: PortableText | null;
}> | null;
// Variable: pricesShortQuery
// Query: *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[] {servicesKey,    "list":list[]{price, lowerPriceLimit, discountPrice, lowerDiscountLimit}}
export type PricesShortQueryResult = Array<{
    servicesKey: ServicesKey | null;
    list: Array<{
        price: number | null;
        lowerPriceLimit: boolean | null;
        discountPrice: number | null;
        lowerDiscountLimit: boolean | null;
    }> | null;
}> | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
    interface SanityQueries {
        '\n    *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[]\n {servicesKey, "servicesName": servicesName[_key == $language][0].value, linkToPage, \n   "list":list[]{new, price, lowerPriceLimit, discountPrice, lowerDiscountLimit, specialPrice,\n                 "serviceName": serviceName[_key == $language][0].value,\n                 "serviceDescription":serviceDescription[_key == $language][0].value}, \n   "servicesDescription":servicesDescription[_key == $language][0].value }': PricesPageQueryResult;
        '\n    *[_type == "pricesPage" && !(_id in path("drafts.**"))][0].priceBlocks[]\n {servicesKey, \n   "list":list[]{price, lowerPriceLimit, discountPrice, lowerDiscountLimit}}': PricesShortQueryResult;
    }
}
