import type { MetadataRoute } from "next";

import { sanityFetch } from "@/sanity/lib/live";
import { blogMetaSlugsQuery, doctorMetaSlugsQuery } from "@/sanity/lib/queries";
export const dynamic = "force-static";
export const revalidate = 3600;

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
    const baseUrl = process.env.NEXT_PUBLIC_BASE_URL;
    const now = new Date("2026-01-01");

    const blogsSlugsList = await sanityFetch({
        query: blogMetaSlugsQuery,
        params: {},
        tags: ["blog"],
    });

    const blogsSlugs = blogsSlugsList.data.flatMap(item => [
        {
            url: `${baseUrl}/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/en/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/ru/blog/${item}`,
            lastModified: now,
            changeFrequency: "weekly" as const,
            priority: 0.5,
        },
    ]);

    const doctorsSlugsList = await sanityFetch({
        query: doctorMetaSlugsQuery,
        params: {},
        tags: ["doctor"],
    });

    const doctorsSlugs = doctorsSlugsList.data.flatMap(item => [
        {
            url: `${baseUrl}/oftalmolohy/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/en/ophthalmologists/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
        {
            url: `${baseUrl}/ru/oftalmologi/${item}`,
            lastModified: now,
            changeFrequency: "monthly" as const,
            priority: 0.5,
        },
    ]);

    return [
        {
            url: `${baseUrl}/`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 1.0,
        },
        {
            url: `${baseUrl}/posluhy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/rayner-galaxy-ua`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/tsiny`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/aktsiyi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/oftalmolohy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/pro-kliniku`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/informatsiya-dlya-patsiyentiv`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/vidhuky`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/kontakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        // послуги
        {
            url: `${baseUrl}/posluhy/lazerna-korekcziya-zoru`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/perevirka-zoru`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/likuvannya-katarakti`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/syndrom-sukhoho-oka`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/dityache-viddilennya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/likuvannya-keratokonusa`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/lazerne-likuvannya-zahvoryuvan-oka`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/refrakczijna-lensektomiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/vitreoretinalna-hirurgiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/intravitrealni-inekczii`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/hirurgichne-likuvannya-glaukomi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/likuvannya-kosookosti`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/hirurgiya-povik-i-konyunktivi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/anesteziologichnij-posibnik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/posluhy/ksenonoterapiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/en`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/ru`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/files/serteficate.pdf`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/politika-konfidenczijnosti`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/files/Британский_офтальмологический_центр.pdf`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.8,
        },
        {
            url: `${baseUrl}/en/services`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/rayner-galaxy-a-new-level-of-vision-is-now-available-at-our-clinic`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/rayner-galaxy-novoe-izmerenie-zreniya-uzhe-v-nashej-klinike`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/service-prices`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/ceny`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/files/plati_chastinami__rozstrochka_•_a_bank.pdf`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/offers`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/akcii`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/ophthalmologists`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/oftalmologi`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/about-clinic`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/o-klinike`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/patient-information`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/informatsiya-dlya-patsiyentov`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/informatsiya-dlya-inohorodnikh-patsiyentiv`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/informatsiya-dlya-patsiyentiv-pered-mikrokhirurhichnym-vtruchannyam`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/preparation-for-surgery-for-strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/reminder-before-a-comprehensive-pediatric-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/patient-information-before-IPL-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/pamyatka-patsiyenta-pered-vitreoretynalnoyu-khirurhiyeyu`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/instruktsiyi-pislya-lazernoyi-korektsiyi-zoru`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/pamyatka-patsiyenta-pislya-khirurhiyi-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/glaukoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/presbiopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/dalekozorist`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/katarakta`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/simptomi-zahvoryuvannya-ochej`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/kosookist`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/korotkozorist-miopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/zakhvoryuvannya-ochey/astigmatizm`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/reviews`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/otzyvy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/contacts`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/kontakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/laser-vision-correction`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/posluhy/lazerna-korekcziya-zoru/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/posluhy/lazerna-korekcziya-zoru/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/eye-exam`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/proverka-zreniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/cataract-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lechenie-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/posluhy/likuvannya-katarakti/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/posluhy/likuvannya-katarakti/iq-life-3d-vodnij-potik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/dry-eye-syndrome`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lechenie-sindroma-suhogo-glaza`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/children-department`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/detskoye-otdeleniye`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/keratoconus-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lecheniye-keratokonusa`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/laser-treatment-of-eye-diseases`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernoye-lecheniye-zabolevaniy-glaza`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/refractive-lensectomy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/intraokuliarnaya-korrekciya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/vitreoretinal-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/vitreoretinalnaya-khirurgiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/intravitreal-injections`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/intravitrealnyye-inyektsii`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/surgical-glaucoma-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/khirurgicheskoye-lecheniye-glaukomy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/strabismus-treatment`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/lecheniye-kosoglaziya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/eyelid-and-conjunctival-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/khirurgiya-vek-i-konyunktivy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/anesthesia-benefit`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/anesteziologicheskoye-posobiye`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/services/xenon-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/uslugi/ksenonoterapiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/privacy-policy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/blog`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/ru/privacy-policy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.64,
        },
        {
            url: `${baseUrl}/en/information-for-nonresident-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/information-for-patients-prior-to-microsurgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/preparation-for-surgery-for-strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/reminder-before-a-comprehensive-pediatric-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/patient-information-before-IPL-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/patient-reminder-before-vitreoretinal-surgery`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/instructions-after-laser-vision-correction`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/pamyatka-patsiyenta-pislya-khirurhiyi-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/glaucoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/presbyopia`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/farsightedness`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/cataract`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/symptoms-of-eye-disease`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/nearsightedness-myopia`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/eye-diseases/astigmatism`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/inogorodnim-patsiyentam`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/reminders-and-instructions-for-patients`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/informatsiya-dlya-patsiyentov-pered-mikrokhirurgicheskim-vmeshatelstvom`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/preparation-for-surgery-for-strabismus`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/reminder-before-a-comprehensive-pediatric-examination`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/patient-information-before-IPL-therapy`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/pamyatki-patsiyentu-pered-vitreoretinalnoy-khirurgiyey`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/instruktsii-posle-korrektsii-zreniya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/pamyatki-paczienta-posle-hirurgii-katarakty`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/glaukoma`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/presbiopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/dalnozorkost`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/katarakta`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/simptomy-zabolevaniya-glaz`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/kosoglazie`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/blizorukost-miopiya`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/glaznye-bolezni/astigmatizm`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/laser-vision-correction/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/laser-vision-correction/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya/iq-lasik-oxygen-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lazernaya-korrekciya-zreniya/sportlife-lasik`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/cataract-treatment/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/en/services/cataract-treatment/iq-life-3d-water-flow`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lechenie-katarakty/iq-5-minutes`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        {
            url: `${baseUrl}/ru/uslugi/lechenie-katarakty/iq-life-3d`,
            lastModified: now,
            changeFrequency: "yearly",
            priority: 0.51,
        },
        ...blogsSlugs,
        ...doctorsSlugs,
    ];
}
